/**
 * Portway PaaS — Nixpacks & OCI Manifest Generator (R2 Core)
 * Transforms detected runtime specifications into deterministic 4-phase
 * Nixpacks build plans (setup, install, build, start) and OCI-compliant container manifests.
 */

import type { DetectedRuntime } from "./detector";

export interface NixpacksPhaseConfig {
  pkgs?: string[];
  aptPkgs?: string[];
  cmds?: string[];
  cacheDirectories?: string[];
  dependsOn?: string[];
}

export interface NixpacksPlan {
  providers: string[];
  buildImage: string;
  variables: Record<string, string>;
  phases: {
    setup: NixpacksPhaseConfig;
    install: NixpacksPhaseConfig;
    build: NixpacksPhaseConfig;
    start: { cmd: string };
  };
  start: {
    cmd: string;
  };
  dockerfile: string;
}

export interface BuildOptions {
  buildCommand?: string;
  startCommand?: string;
  installCommand?: string;
  port?: number;
  variables?: Record<string, string>;
  rootDir?: string;
  customDockerImage?: string;
}

/**
 * Generates an OCI-compliant multi-stage Dockerfile from a NixpacksPlan or DetectedRuntime
 */
export function generateOciManifest(
  runtime: DetectedRuntime,
  planPhases: NixpacksPlan["phases"],
  options?: BuildOptions
): string {
  const targetPort = options?.port ?? runtime.defaultPort ?? 8080;
  const startCmd = options?.startCommand || planPhases.start.cmd || runtime.startCommand;

  // If user provided raw dockerfile, return it
  if (runtime.language === "dockerfile" && runtime.dockerfile) {
    return runtime.dockerfile;
  }

  // Multi-stage OCI manifest tailored to runtime
  switch (runtime.language) {
    case "nodejs": {
      const pm = runtime.packageManager || "npm";
      const installCmd = options?.installCommand || (planPhases.install.cmds?.[0] ?? `${pm} install`);
      const buildCmd = options?.buildCommand !== undefined ? options.buildCommand : (planPhases.build.cmds?.[0] ?? "");

      return `# Generated by Portway Nixpacks Engine (Node.js)
FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat ca-certificates
ENV NODE_ENV=production
ENV PORT=${targetPort}

FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* bun.lockb* ./
RUN ${installCmd}

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
${buildCmd ? `RUN ${buildCmd}` : "# No build command required"}

FROM base AS runner
WORKDIR /app
COPY --from=builder /app ./
EXPOSE ${targetPort}
CMD ["sh", "-c", "${startCmd}"]
`;
    }

    case "python": {
      const installCmd = options?.installCommand || (planPhases.install.cmds?.[0] ?? "pip install --no-cache-dir -r requirements.txt");

      return `# Generated by Portway Nixpacks Engine (Python)
FROM python:3.11-slim AS base
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev ca-certificates && rm -rf /var/lib/apt/lists/*
ENV PYTHONUNBUFFERED=1
ENV PORT=${targetPort}

COPY requirements.txt* Pipfile* pyproject.toml* setup.py* ./
RUN ${installCmd}

COPY . .
EXPOSE ${targetPort}
CMD ["sh", "-c", "${startCmd}"]
`;
    }

    case "go": {
      const buildCmd = options?.buildCommand || "go build -ldflags=\"-s -w\" -o /app/server .";

      return `# Generated by Portway Nixpacks Engine (Go)
FROM golang:1.22-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git ca-certificates
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux ${buildCmd}

FROM alpine:3.19 AS runner
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/server /app/server
ENV PORT=${targetPort}
EXPOSE ${targetPort}
CMD ["sh", "-c", "${startCmd}"]
`;
    }

    case "rust": {
      return `# Generated by Portway Nixpacks Engine (Rust)
FROM rust:1.78-slim AS builder
WORKDIR /app
RUN apt-get update && apt-get install -y pkg-config libssl-dev gcc && rm -rf /var/lib/apt/lists/*
COPY Cargo.toml Cargo.lock* ./
COPY src/ ./src/
RUN cargo build --release

FROM debian:bookworm-slim AS runner
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates libssl-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release /app/bin
ENV PORT=${targetPort}
EXPOSE ${targetPort}
CMD ["sh", "-c", "${startCmd}"]
`;
    }

    case "ruby": {
      return `# Generated by Portway Nixpacks Engine (Ruby)
FROM ruby:3.2-slim AS base
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev git && rm -rf /var/lib/apt/lists/*
ENV PORT=${targetPort}

COPY Gemfile Gemfile.lock* ./
RUN bundle install

COPY . .
EXPOSE ${targetPort}
CMD ["sh", "-c", "${startCmd}"]
`;
    }

    default: {
      return `# Generated by Portway Nixpacks Engine (Generic)
FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY . .
ENV PORT=${targetPort}
EXPOSE ${targetPort}
CMD ["sh", "-c", "${startCmd}"]
`;
    }
  }
}

/**
 * Generates a full 4-phase Nixpacks plan from runtime detection.
 * Satisfies PROJECT.md contract:
 * `generateNixpacksPlan(runtime: DetectedRuntime, options?: BuildOptions): NixpacksPlan`
 */
export function generateNixpacksPlan(
  runtime: DetectedRuntime,
  options?: BuildOptions
): NixpacksPlan {
  const targetPort = options?.port ?? runtime.defaultPort ?? 8080;
  const buildCmd = options?.buildCommand !== undefined ? options.buildCommand : runtime.buildCommand;
  const startCmd = options?.startCommand || runtime.startCommand;
  const installCmd = options?.installCommand || runtime.installCommand;

  const providers: string[] = [runtime.language];
  if (runtime.framework && runtime.framework !== runtime.language) {
    providers.push(runtime.framework);
  }

  // 1. Setup Phase
  const setupPhase: NixpacksPhaseConfig = {
    pkgs: runtime.systemPackages || [],
    aptPkgs: ["ca-certificates"],
  };

  // 2. Install Phase
  const installPhase: NixpacksPhaseConfig = {
    cmds: installCmd ? [installCmd] : [],
    cacheDirectories:
      runtime.language === "nodejs"
        ? ["/root/.npm", "/root/.cache/yarn", "/root/.local/share/pnpm"]
        : runtime.language === "python"
        ? ["/root/.cache/pip"]
        : runtime.language === "rust"
        ? ["/usr/local/cargo/registry"]
        : [],
    dependsOn: ["setup"],
  };

  // 3. Build Phase
  const buildPhase: NixpacksPhaseConfig = {
    cmds: buildCmd ? [buildCmd] : [],
    cacheDirectories: runtime.framework === "nextjs" ? [".next/cache"] : [],
    dependsOn: ["install"],
  };

  // 4. Start Phase
  const startPhase = {
    cmd: startCmd,
  };

  const variables: Record<string, string> = {
    PORT: String(targetPort),
    NODE_ENV: "production",
    ...(options?.variables || {}),
  };

  const phases = {
    setup: setupPhase,
    install: installPhase,
    build: buildPhase,
    start: startPhase,
  };

  const dockerfile = generateOciManifest(runtime, phases, options);

  return {
    providers,
    buildImage: options?.customDockerImage || `ghcr.io/railpack/${runtime.language}:latest`,
    variables,
    phases,
    start: startPhase,
    dockerfile,
  };
}
